### ISSUE TITLE
Hey would you like put a license on this repo?

### ISSUE THREAD

**Issue by freemin7** [monstermuqian/optimization_study#1]
I'm also interested in similar topics but in a different programming language, Julia.
However if your code does not have a license, i literally can't take a look at it due to copyright stuff.
If you were to put a license on it, i could take a look/translate it to other language.

If you are unfamiliar with software licenses i can help you with that.

**Comment by monstermuqian** [comment]
Thank you for you interest ! I would like to provide a software licenses so that you can translate it in Julia. But I dont know how to do that. So I am willing to get help from you to learn how to do that.

**Comment by freemin7** [comment]
Ok, so the way that would be most helpful is that you put your complete repository under a license. The idea is that everybody can use your repo with in the terms of your choosing (and you wouldn't have to be asked, so it might even help people after you are dead).

The moment someone reads your code and implements something vaguely based on it they probably made a derivative of your code. This includes modifying, copying and giving it to other people (printing it out and giving it someone else to read would require your permission), translating it, fixing bugs or using your code as inspiration. By writing a piece of code and putting it online you are the creator and nobody is allowed to do something with it unless you agree to it or are dead for over 70 years. If this sounds odd or broken, it's just how copyright works.

This series of question might help you choose a license:

If someone modifies/copies/translates/uses-your-code-as-inspiration do you want their repository to say that it is based on your work? ( attribution )

 - If no i recommend the 0BSD license, it is a small, easy understood license i personally use a lot but it is extremely liberal, maybe to liberal for you. This is license is basically saying, anybody can do with my code 
what they want, don't sue me.

If yes, do you want derivatives to be under the same license? ( receprocity )

 - If no, i recommend the MIT License which is used a lot in the Julia community.

If yes, should the anybody in case he distributes an executable on your source code have to also distribute a copy of their (modified) source code that uses your code? ( force redistribution of modified source in case someone makes something with it )

 - If no, i'd recommend the Mozilla Public License 2.0 compared to the GPL family, you don't have to license other code under the GPL if you distribute them together. Compared to the MIT, any derivative work (even a complete rewrite) will stay licensed under the Mozilla Public License 2.0.
 - If yes, This leaves you with the GPL family of licenses. Those are considered super strict.

If you have any questions let me know.

If you have any think you have decided on a license, just Google it and read it and see if you understand it and like it. Note that all those licenses allow people to make money from your code. For example if i would translate your code to Julia, develop that code base for 12 years and later decide to commercialize some software that uses that Julia code under the hood parts of my program would still be bound by the license you choose now.
I think this example is purely hypothetical.
If you don't want that even be a possibility i would have to look into licenses which forbid commercial use. Those are really uncommon in open source software.

**Comment by freemin7** [comment]
You can also ask stuff in German if you prefer.

**Comment by monstermuqian** [comment]
Danke für Ihre ausführliche Erklärung! Ich werde das MIT-Licenses benutzen und ich stelle es jetzt ein.   :)

**Comment by freemin7** [comment]
Awesome.
